In [1]:
# Webscrape Shanghai Rankings
# Subject Rankings

import os
import re
import sys
import csv
from bs4 import BeautifulSoup as bs
import requests, matplotlib.pyplot
import numpy as np
import pandas as pd
from urllib.request import urlopen

In [2]:
header = []
school_name = []
score = []
location = []
acceptance_rate = []

In [3]:
# Specify url and open website
url = "http://www.shanghairanking.com/ARWU2017.html"
page = requests.get(url)
page = page.text

## Start parsing raw data. Storing and cleaning after

In [4]:
# Use page to create a BeautifulSoup object and specify the type of parser
# Raw data
soup = bs(page, 'html.parser')
#soup = bs(page,"lxml")

In [5]:
# Parse raw_data
raw_data = soup.select('div')
raw_data = [s.text for s in soup.select('div')]

In [6]:
# raw_data dataframe
Raw = pd.DataFrame(raw_data)

In [ ]:
# Raw data to csv
Raw.to_csv("raw_data_Shanghai_2017.csv", sep=',', encoding='utf-8')

In [7]:
# Cleaning raw data

header = [s.text for s in soup.select("tr > th")]
loc = soup.select('td > a > img')  # Finding location
school_name = [s.text for s in soup.select("tr > td > a")]  #Raw school names
school_name = school_name[0::2]

# Raw scores, ranking, total score and award staff
score = [s.text for s in soup.select("tr > td > div")]
nat_ranking = score[0::8] # National Ranking
total_score = score[1::8] # Overall Ranking
award_staff = score[3::8] # Staff awarded Nobel Prize while at institution
# score variable 5 scores per school
# First: Total Score
# Second: Highly Cited Researchers
# Third: Papers indexed in Science citations
# Fourth: Papers published in Top 20% Journals
# Fifth: Expenditures / Funding

In [8]:
# Create pandas dataframe
Schools = pd.DataFrame({"Total Score": total_score, "National Ranking": nat_ranking, "Staff Awarded Nobel Prize": award_staff, "School Name": school_name, "Location": loc})
Schools

,Location,National Ranking,School Name,Staff Awarded Nobel Prize,Total Score
0,"<img src=""image/flag/USA.png""/>",1,Harvard University,100.0,100.0
1,"<img src=""image/flag/USA.png""/>",2,Stanford University,88.5,76.5
2,"<img src=""image/flag/UK.png""/>",1,University of Cambridge,95.4,70.9
3,"<img src=""image/flag/USA.png""/>",3,Massachusetts Institute of Technology (MIT),82.3,70.4
4,"<img src=""image/flag/USA.png""/>",4,"University of California, Berkeley",78.4,69.1
5,"<img src=""image/flag/USA.png""/>",5,Princeton University,97.9,61.1
6,"<img src=""image/flag/UK.png""/>",2,University of Oxford,54.2,60.1
7,"<img src=""image/flag/USA.png""/>",6,Columbia University,65.1,58.8
8,"<img src=""image/flag/USA.png""/>",7,California Institute of Technology,65.8,57.3
9,"<img src=""image/flag/USA.png""/>",8,University of Chicago,85.1,53.9
10,"<img src=""image/flag/USA.png""/>",9,Yale University,49.7,52.8
11,"<img src=""image/flag/USA.png""/>",10,"University of California, Los Angeles",46.4,52.5
12,"<img src=""image/flag/USA.png""/>",11,University of Washington,37.4,50.3
13,"<img src=""image/flag/USA.png""/>",12,Cornell University,49.1,49.6
14,"<img src=""image/flag/USA.png""/>",13,"University of California, San Diego",35.1,49.5
15,"<img src=""image/flag/UK.png""/>",3,University College London,35.8,47.1
16,"<img src=""image/flag/USA.png""/>",14,University of Pennsylvania,33.4,46.0
17,"<img src=""image/flag/USA.png""/>",15,Johns Hopkins University,33.2,45.7
18,"<img src=""image/flag/Switzerland.png""/>",1,Swiss Federal Institute of Technology Zurich,35.1,44.1
19,"<img src=""image/flag/USA.png""/>",16,Washington University in St. Louis,24.6,43.3
20,"<img src=""image/flag/USA.png""/>",17,"University of California, San Francisco",39.4,42.4
21,"<img src=""image/flag/USA.png""/>",18,Northwestern University,27.6,41.9
22,"<img src=""image/flag/Canada.png""/>",1,University of Toronto,17.0,41.6
23,"<img src=""image/flag/Japan.png""/>",1,The University of Tokyo,25.0,41.5
24,"<img src=""image/flag/USA.png""/>",19,University of Michigan-Ann Arbor,0.0,41.5
25,"<img src=""image/flag/USA.png""/>",20,Duke University,19.0,41.0
26,"<img src=""image/flag/UK.png""/>",4,Imperial College London,35.4,40.9
27,"<img src=""image/flag/USA.png""/>",21,University of Wisconsin - Madison,34.3,39.7
28,"<img src=""image/flag/USA.png""/>",22,New York University,31.5,38.6
29,"<img src=""image/flag/Denmark.png""/>",1,University of Copenhagen,18.6,38.5
...,...,...,...,...,...
470,"<img src=""image/flag/Switzerland.png""/>",8,University of Fribourg,0.0,
471,"<img src=""image/flag/Germany.png""/>",27-37,University of Hannover,0.0,
472,"<img src=""image/flag/Iceland.png""/>",1,University of Iceland,0.0,
473,"<img src=""image/flag/SouthAfrica.png""/>",3-5,University of Johannesburg,0.0,
474,"<img src=""image/flag/Germany.png""/>",27-37,University of Konstanz,0.0,
475,"<img src=""image/flag/SouthAfrica.png""/>",3-5,University of KwaZulu-Natal,0.0,
476,"<img src=""image/flag/Slovenia.png""/>",1,University of Ljubljana,0.0,
477,"<img src=""image/flag/Malaysia.png""/>",1-2,University of Malaya,0.0,
478,"<img src=""image/flag/Germany.png""/>",27-37,University of Marburg,0.0,
479,"<img src=""image/flag/Portugal.png""/>",3-5,University of Minho,0.0,
480,"<img src=""image/flag/USA.png""/>",120-135,University of Montana - Missoula,0.0,
481,"<img src=""image/flag/USA.png""/>",120-135,University of New Hampshire - Durham,0.0,
482,"<img src=""image/flag/France.png""/>",18-20,University of Nice Sophia Antipolis,0.0,
483,"<img src=""image/flag/USA.png""/>",120-135,University of Oklahoma - Norman,0.0,
484,"<img src=""image/flag/Finland.png""/>",3-5,University of Oulu,0.0,
485,"<img src=""image/flag/Italy.png""/>",13-16,University of Palermo,0.0,
486,"<img src=""image/flag/Germany.png""/>",27-37,University of Potsdam,0.0,
487,"<img src=""image/flag/Germany.png""/>",27-37,University of Regensburg,0.0,
488,"<img src=""image/flag/Germany.png""/>",27-37,University of Rostock,0.0,
489,"<img src=""image/flag/Malaysia.png""/>",1-2,"University of Science, Malaysia",0.0,
490,"<img src=""image/flag/Spain.png""/>",8-11,University of the Basque Country,0.0,
491,"<img src=""image/flag/Italy.png""/>",13-16,University of Trieste,0.0,
492,"<img src=""image/flag/Finland.png""/>",3-5,University of Turku,0.0,
493,"<img src=""image/flag/Spain.png""/>",8-11,University of Valencia,0.0,
494,"<img src=""image/flag/USA.png""/>",120-135,University of Wyoming,0.0,
495,"<img src=""image/flag/Austria.png""/>",4,Vienna University of Technology,0.0,
496,"<img src=""image/flag/Italy.png""/>",13-16,Vita-Salute San Raffaele University,0.0,
497,"<img src=""image/flag/USA.png""/>",120-135,Washington State University,0.0,
498,"<img src=""image/flag/USA.png""/>",120-135,West Virginia University,0.0,
499,"<img src=""image/flag/China.png""/>",34-45,Wuhan University of Technology,0.0,

In [ ]:
# Cleaned data to csv
# Schools.to_csv("Clean_data_Shanghai_2017.csv", sep=',', encoding='utf-8')